### ISSUE TITLE
add bower.json

### ISSUE THREAD

**Issue by zeroxme** [jakiestfu/Blur.js#14]
please add bower.json and register it in bower

**Comment by CezaryDanielNowak** [comment]
Bower.json is added in my fork: https://github.com/korpirkor/Blur.js

**Comment by zeroxme** [comment]
ok please do a pull request so he can merge it to the main repo

**Comment by dangelion** [comment]
+1 !!!

**Comment by CezaryDanielNowak** [comment]
@zeroxme, there is one already :) https://github.com/jakiestfu/Blur.js/pull/37/files
Looks like this repo is not maintained, feel free to use this one:

```
bower install --save https://github.com/CezaryDanielNowak/Blur.js/archive/0.2.0.tar.gz
```

**Comment by zeroxme** [comment]
alright thanks @CezaryDanielNowak
