### ISSUE TITLE
dynamic background without draggable ?

### ISSUE THREAD

**Issue by daslicht** [jakiestfu/Blur.js#4]
Hello,
is there a way to have the draggable background behavior 
but without being able to drag the div ?

This would be awesome helpful if you have a fullscreen background image but want to keep things look transparent when resizing the page.

Best Regards
Marc

**Comment by jakiestfu** [comment]
@daslicht I am not supporting this plugin anymore because it is only an experiment. Using this script in production would not be recommended, and it was initially created to see if it was even possible. Sorry for any inconveniences!:(
